### ISSUE TITLE
MacOS installer signing fails with error code 109

### ISSUE THREAD

**Issue by jaimergp** [napari/packaging#11]
Just writing down that macos PKG signing for the bundles [has been failing for a while](https://github.com/napari/napari/actions/workflows/make_bundle_conda.yml?page=2&query=event%3Aschedule) (a month or so). Need to debug locally. The error code (109) is undocumented. Certificate import does work (previous step in CI) so it might be that:

* Certificate has been revoked so it cannot be used for signing
* Timestamp server is rejecting calls from CI
* Something else?

I'll tackle this in `napari/packaging`.

**Comment by jaimergp** [comment]
I found out why. Turns out the conda environment now contains a `codesign` executable that some package might have added. The fix: get it out of the way so it doesn't clobber Apple's `codesign` T_T

**Comment by Czaki** [comment]
Maybe do `which codesign` to determine a proper path (and save on variable) before setup conda?

**Comment by jaimergp** [comment]
See [#4903](https://github.com/napari/napari/pull/4903) for my suggested fix!

**Comment by potating-potato** [comment]
this seems addressed now
