### ISSUE TITLE
Change Bundle Qt backend to PyQt5 

### ISSUE THREAD

**Issue by Czaki** [napari/packaging#13]
## 🚀 Feature

Change backend of the bundled app to PyQt5 

## Motivation

PyQt5 in version 5.15.4 is released in conda-forge https://anaconda.org/conda-forge/pyqt 
PySide2 is still available in version 5.13.2 which uses Qt in version 5.12.9. 
Switching to PyQt5 should reduce the problems with lack of features in old  Qt bindings releases (for example QComboBox.addItems for new version accept iterators (ex. `dict.keys()`), but PySide2 from the conda forge do not accept.

**Comment by potating-potato** [comment]
now that we are switching to the installer approach, I wonder if we can make the qt backend a configurable option for users to decide while maintaining a community consensus default?

**Comment by psobolewskiPhD** [comment]
FYI, `pyside2` is now at 5.15.5 on conda-forge, including arm64 macOS binaries:
```
Executing the query pyside2

conda-forge/osx-arm64                              @   2.9MB/s  1.1s
conda-forge/noarch                                 @   3.7MB/s  2.6s


 Name    Version Build           Channel              
───────────────────────────────────────────────────────
 pyside2 5.15.5  py310h5219f08_1 conda-forge/osx-arm64
 pyside2 5.15.5  py38h465b20c_1  conda-forge/osx-arm64
 pyside2 5.15.5  py39h46bc059_1  conda-forge/osx-arm64
```

**Comment by Czaki** [comment]
Yes. Pyside is present. But this still does not solve the problem of small differences between bindings API; writing some type of test is hard, and using different bindings may cause while manually testing, some bugs may be missed when the bundle is targeted for less experienced users. 

So from my perspective still proper solution is to change the default backend or request all core dev to change their development environment.

**Comment by jaimergp** [comment]
Thanks for the heads up @psobolewskiPhD! Now I can finally remove a couple of ugly workarounds we had in the scripts.

**Comment by jaimergp** [comment]
> now that we are switching to the installer approach, I wonder if we can make the qt backend a configurable option for users to decide while maintaining a community consensus default?

We _could_ build installers for both bindings, and let people download whatever they want, but that's a bit of a waste of space, I feel? We prefer pyside on the installer due to the more permissive license, but afaik that's the only reason.

**Comment by goanpeca** [comment]
I do not think we should be changing this, so I think we could close this issue.
