### ISSUE TITLE
Anaconda.org token needed in this repo

### ISSUE THREAD

**Issue by jaimergp** [napari/packaging#19]

**Comment by potating-potato** [comment]
@jaimergp can you please provide more details? I think @sofroniewn may be able to help here

**Comment by jaimergp** [comment]
The secret that stores the anaconda.org token is a repository token (not an organization one), so we don't have access to the same one we use at `napari/napari`. I can always mint another one, but I don't have admin access in this repo, so I can't add it.

**Comment by potating-potato** [comment]
> The secret that stores the anaconda.org token is a repository token (not an organization one), so we don't have access to the same one we use at `napari/napari`. I can always mint another one, but I don't have admin access in this repo, so I can't add it.

do you happen to know the name of it in the main repo? We can ask Nick to copy it to this repo

**Comment by jaimergp** [comment]
Should be [`ANACONDA_TOKEN`](https://github.com/napari/napari/blob/a23740339b1e78822f6c6996f05973d3f5bef2df/.github/workflows/make_bundle_conda.yml#L141)

**Comment by potating-potato** [comment]
is this still relevant now that we are using credentials from the main repo in the workflow?

**Comment by jaimergp** [comment]
Not anymore, we are just inheriting things now :D
