### ISSUE TITLE
[nightly] Nightly is >12 days old and installs wrong app-model

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/packaging#194]
See here:
https://anaconda.org/napari/napari
>12 days ago
Using `conda create -n napari-main -c "napari/label/nightly" -c conda-forge napari python=3.12 pyqt`
I get:
```
  app-model          conda-forge/noarch::app-model-0.2.8-pyhd8ed1ab_0 
```
Which leads to an error, because the napari is indeed new enough to require 0.3.0

**Comment by psobolewskiPhD** [comment]
It's wierd, because the recipe in this repo was updated >1 month ago:
https://github.com/napari/packaging/pull/184

And if I do a plain install: `conda create -n napari-main -c conda-forge napari python=3.12 pyqt`
I get the correct version:
```
  app-model          conda-forge/noarch::app-model-0.3.0-pyhd8ed1ab_0 
```

**Comment by psobolewskiPhD** [comment]
OK, the >12 day version is I think because napari/napari main hasn't been updated, so the upload is skipped.
https://github.com/napari/napari/actions/runs/11646878241/job/32431454579#step:13:40
So what's wierd is the app-model version.
The most recent build does use the correct recipe?
https://github.com/napari/napari/actions/runs/11646878241/job/32431454579#step:9:5717

**Comment by psobolewskiPhD** [comment]
I've merged a PR and re-run the workflow:
https://github.com/napari/napari/actions/runs/11646878241
Hopefully it's correct?

**Comment by psobolewskiPhD** [comment]
Nope.
Also, I just noticed the nightly I got is:
```
  napari             napari/label/nightly/noarch::napari-0.5.4.dev40+gc10dc9fe-hd8ed1ab_0 
```
which is from a month ago, so that explains it. 
It must be something related to tags? the newer upload is marked as `rc4`, which matches the latest run:
https://github.com/napari/napari/actions/runs/11646878241/job/32449296763#step:13:36

**Comment by psobolewskiPhD** [comment]
Ok, so re-running it doesn't do anything because uploads are just from scheduled. I'll wait till tomorrow.

**Comment by jaimergp** [comment]
We are hitting [this conda issue](https://github.com/conda/conda/issues/12568) I think. Let me patch this in our scripts.

**Comment by jaimergp** [comment]
I also marked the `0.5.4.devX` stuff as broken so they are not seen by the solver.

**Comment by psobolewskiPhD** [comment]
I now get:
```
  + napari                             0.5.4rc4  hd8ed1ab_0            napari/label/nightly        8kB
```
Which pulls
```
  + app-model                             0.3.0  pyhd8ed1ab_0          conda-forge              Cached
```

So it appears the latest nightly is properly used.
