### ISSUE TITLE
UX/UI workflow for bundles updates

### ISSUE THREAD

**Issue by goanpeca** [napari/packaging#21]
### Overview of design need

The bundle application will implement an update mechanism, that is when there is a new version of napari (conda) pakage, the UI will informa the user that there is a new version available and ask if the user wants to install it or not.

#### When?

This checks could be performed on startup (before the napari window loads) or after the napari windows loads.

#### Settings

There will be some settings to control this for the user

`Check for updates on startup: Always/Never... etc`
`Check for release (alpha/beta/rc?)candidates when checking for updates [ ] Checkbox`

#### Menus

Some apps include a `check for updates` action on the application (mac) or help (linux/win) menus that can trigger a manual check.

<img width="291" alt="Screen Shot 2022-02-18 at 9 31 31 AM" src="https://user-images.githubusercontent.com/3627835/154701924-72747229-06da-45db-be97-182c9d49db33.png">

#### UI elements

- There is a new update, do you want to update (in the background) ? Yes/No? checkbox dont ask again, or always do the same option?
- Depending on the result of the update (successful, unsuccessful) the User might be prompted to:
    - Restart and use the new version
    - Continue working on the current one (the next time napari is started the new version will be started)
    - Inform the user of any issues/errors that might have occurred.

### What level of design is needed? (Choose all that apply)

- [ ] **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [ ] **information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [x] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ]  **Yes:** engineering cannot proceed without a design first
- [x] **No:** engineering can create a first version, and design can come in later to iterate and refine

**Comment by potating-potato** [comment]
Given the feedback I am going to close this issue, the new design to address the the update workflow will be captured in napari #4952
