### ISSUE TITLE
macOS bundle build failing

### ISSUE THREAD

**Issue by jni** [napari/packaging#212]
Here:

https://github.com/napari/napari/actions/runs/12272453640/job/34241507315#step:20:88

(the same error appears for the non-ARM build)

The error is:

```
+ xcrun notarytool submit /Users/runner/work/napari/napari/napari-packaging/_work/napari-0.5.5rc1-macOS-arm64.pkg --apple-id *** --password *** --team-id *** --output-format json --wait --timeout 30m
+ tee /Users/runner/work/_temp/napari-0.5.5rc1-macOS-arm64.pkg.notarization.json
Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.
+ notary_exit_code=1
+ set -e
+ [[ 1 != 0 ]]
++ jq -r .id /Users/runner/work/_temp/napari-0.5.5rc1-macOS-arm64.pkg.notarization.json
+ submission_id=
+ xcrun notarytool log '' --apple-id *** --password *** --team-id ***
Error: The value '' is invalid for '<submission-id>':  must be a valid UUID
Help:  <submission-id>  Notary Submission ID (UUID)
Usage: notarytool log [<options>] <submission-id> <output-path>
  See 'notarytool log --help' for more information.
```

I remember going through this before. @jaimergp is there documentation on the process we need to go through here? I promise to pay more attention this time. 😅

**Comment by jaimergp** [comment]
Someone at CZI has to log in their Apple Developer Portal and click Agree on whatever prompt they are offering this time.

Ideally these certificates would be minted by Numfocus, but that's a separate question.

**Comment by kephale** [comment]
I've poked CZI folks about approving this.

**Comment by kephale** [comment]
This should be resolved on the CZI side now.

**Comment by psobolewskiPhD** [comment]
I re-ran the workflow 🤞

**Comment by psobolewskiPhD** [comment]
Seems good now
https://github.com/napari/napari/actions/runs/12272453640
