### ISSUE TITLE
Buy a developer certificate for bundle signing

### ISSUE THREAD

**Issue by tlambert03** [napari/packaging#25]
## 🧰 Task
To get rid of the scary "cannot verify developer" messages described in the [bundle install guide](https://napari.org/tutorials/fundamentals/installation#installing-as-a-bundled-app)

See napari/napari#496, napari/napari#1289, napari/napari#1074, napari/napari#3339

**Comment by potating-potato** [comment]
@napari/steering-council just to record the decision as of now here:
Will we obtain a license under napari org and use that instead in our signing process? I am going to close this issue if everyone is onboard to continue with the current CZI license
