### ISSUE TITLE
PermissionsError when accessing some directories with os module

### ISSUE THREAD

**Issue by mrclary** [napari/packaging#38]
## 🐛 Bug

A `PermissionError` is raised when using `os.scandir` with the conda-based application bundle.
I've noticed the same issue with Spyder as well with conda-based application bundle.

This issue only manifests with the three user directories `~/Desktop`, `~/Documents`, and `~/Downloads` (and anything therein). No other directories on the system produce the error.

Interestingly, this issue does _not_ manifest when launching the application executable directly.
```shell
$ ~/Applications/napari\ \(0.4.16rc7\).app/Contents/MacOS/napari_\(0.4.16rc7\)
```

I've observed identical behavior on two separate machines:
- iMac with arm64 running 12.5.1
- Macbook Pro with x86_64 running 12.5.1

## To Reproduce

1. Launch condo-based napari application bundle `napari (0.4.16rc7).app` from Finder
2. View the iPython console
3. Attempt `os.scandir` for any of the three user directories `~/Desktop`, `~/Documents`, or `~/Downloads`
4. Observe the error 

```python
In [1]: import os

In [2]: os.scandir('/Users/ryan/')
Out[2]: <posix.ScandirIterator at 0x179e18960>

In [3]: os.scandir('/Users/ryan/Documents/')
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 os.scandir('/Users/ryan/Documents/')

PermissionError: [Errno 1] Operation not permitted: '/Users/ryan/Documents/'
/Users/ryan/Library/napari-0.4.16rc7/envs/napari-0.4.16rc7/lib/python3.9/site-packages/ipykernel/kernelbase.py:751: RuntimeWarning: coroutine 'InProcessKernel._abort_queues' was never awaited!
```

## Environment

napari: 0.4.16rc7
Platform: macOS-12.5.1-x86_64-i386-64bit
System: MacOS 12.5.1
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) [Clang 13.0.1 ]
Qt: 5.15.3
PySide2: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.05.2
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2240x1260, scale 2.0

Plugins:
- console: 0.0.4
- napari-svg: 0.1.6
- scikit-image: 0.4.16rc7

**Comment by jaimergp** [comment]
`osacompile` does not create Mach-O binaries; the compiled files still need to be run with `osascript` so it won't work for our use case. `shc` is not available on conda-forge so if we can avoid that route, better; I am investigating the C-launcher now.

**Comment by jaimergp** [comment]
I have a working launcher written in C [in this PR](https://github.com/conda/menuinst/pull/91). I need to do some tests to see if this is enough to workaround the security limitations, but I am guessing it is? 🤞

**Comment by jaimergp** [comment]
The launcher alone did not work 🤷 
However, if I sign the `shortcut.app` with no certificate (self signed) and some entitlements, it does prompt for permission! I now wonder if we need the C launcher or not, but I guess it won't hurt :D [I added some support here](https://github.com/conda/menuinst/pull/91/commits/b6a5bf987faf0f28e1ce775d3330123eff7cf13f), but I still need to do some more debugging.

**Comment by jaimergp** [comment]
Ok, confirmed both are needed 😅 That's nice to know; the C launcher wasn't in vain!

Look how cute the permissions request is now :) 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2559438/202764859-a06f680a-3906-4b02-bde6-b75399eec2d2.png">

And it appears here in the System Preferences as well:

![image](https://user-images.githubusercontent.com/2559438/202765415-aaa2fd74-44df-4426-a60d-acb9461e69f5.png)

**Comment by goanpeca** [comment]
Lovelly!

**Comment by jaimergp** [comment]
OMG, finally. The latest artifacts in https://github.com/napari/packaging/pull/42 correctly implement permissions for macOS. This will be closed as soon as the work in that PR is cleaned up.

@mrclary, you can use the packages in `napari/label/bundle_tools_2`, which now rely on the latest constructor `main` + the menuinst changes on top. This doesn't need `shc` or anything. A minimal C launcher is bundled.
 
The JSON files support new keys to address your concerns with environment variables, pre-activation logic and entitlements for correct permissions.

Thank you so much for the report and constant feedback!

**Comment by mrclary** [comment]
@jaimergp, great! I'll take a look at implementing for Spyder.
