### ISSUE TITLE
LSEnvironment results in <array> instead of <dict> in info.plist

### ISSUE THREAD

**Issue by mrclary** [napari/packaging#59]
@jaimergp,
https://github.com/napari/packaging/pull/42 added the `LSEnvironment` key to the json schema (yeah!). However, it results in an `<array>` value in `info.plist` instead of `<dict>`.
In testing with Spyder I have the following:

In spyder-menu.json
```json
                "osx": {
                    "CFBundleName": "Spyder",
                    "CFBundleDisplayName": "Spyder",
                    "CFBundleIdentifier": "org.spyder-ide.Spyder",
                    "CFBundleVersion": "__PKG_VERSION__",
                    "LSEnvironment": {
                        "SPYDER_APP": "True"
                    }
                }
```
After installation, in `Spyder.app/Contents/info.plist`
```xml
	<key>LSEnvironment</key>
	<array>
		<string>SPYDER_APP</string>
	</array>
```
I expect it to be 
```xml
	<key>LSEnvironment</key>
	<dict>
		<key>SPYDER_APP</key>
                <string>True</string>
	</dict>
```

Am I incorrect in my implementation of `LSEnvironment` in `spyder-menu.json`? or is this unintended behavior?

**Comment by jaimergp** [comment]
You are absolutely right. It should be a dict. This is the first subkey that is not either a str or list, so we were blindly iterating over the dict, which only return the keys.

Fixed now in https://github.com/conda/menuinst/pull/91/commits/849938c051615e1660335b9f123a0d4e28dcf816! I am repackaging some stuff as we speak so it should be available as soon as I am done with https://github.com/jaimergp-forge/conda-standalone-feedstock/pull/6

**Comment by mrclary** [comment]
Wow! That was fast. That's a big commit to do in less than an hour 😮 🚀

**Comment by jaimergp** [comment]
Hah, you caught me working on `menuinst` today, that's all :) 
Let's see if it works though! The new builds (`40` for menuinst, `3` for conda-standalone) in `napari/label/bundle_tools_2` contain the fixes already, if you want to try.

**Comment by mrclary** [comment]
Looks like the new builds work correctly!

I've also noticed that arguments are no longer provided to the user's post-install script, so `$2` is not available to indicate install location. I don't know if this is intentional, but I'm using `PREFIX` (root conda environment) and `DSTROOT` (system or user `Library`), as these appear to be available.

Additionally, I still need to add a symbolic link to Python in order for keyboard shortcuts in system preferences to work (I'm using this as a proxy for full macOS integration). For example:
```
/Users/rclary/Applications/Spyder.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   ├── python -> /Users/rclary/Library/spyder-5.4.1.dev170/envs/spyder-5.4.1.dev170/bin/python
    │   ├── spyder
    │   └── spyder-script
    ├── PkgInfo
    └── Resources
        └── spyder.icns
```
with `spyder-menu.json`
```
            "precommand": "here=$(dirname \"$0\")",
            "command": ["${here}/python", "${CONDA_PREFIX}/bin/spyder", "$@"],
```
Do you still have the same issue with napari?

**Comment by jaimergp** [comment]
* We standardized the post_install "interface" so we don't need hacky things across platforms. [See docs here](https://github.com/conda/constructor/blob/main/CONSTRUCT.md#post_install). TLDR: Using PREFIX is the right way.
* I am not sure why the `python` symlink is still needed, but I haven't tried to set up napari shortcuts yet. The `spyder` file you see now it's a signed C launcher that calls `spyder-script` in a subprocess. Shouldn't that be enough to keep the process "within the .app directory"? :( If not, I guess we could modify the launcher to accept "arbitrary arguments" of what process to launch, but "arbitrary" and C scares me 😬

**Comment by jaimergp** [comment]
And if that doesn't work, I guess we can temporarily symlink stuff as part of the shortcut logic to keep things in-house. Something like

```python
lines.append(f'ln -s "{command[0]}" "{app_location / "Contents" / "MacOS" / "_symlinked_executable"}"')
# replace command[0] with symlink location and continue the rest of the logic
```

**Comment by jaimergp** [comment]
Also, please note I am not an expert macOS user so I am not aware of many of the UX conventions. Is it to be expected that all applications "register" their keyboard shortcuts in the OS Preferences? 

I might need some guidance :D This is all see in my system:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2559438/209322120-d563448a-593f-4c72-8d7a-316817ee8900.png">

**Comment by mrclary** [comment]
> * We standardized the post_install "interface" so we don't need hacky things across platforms. [See docs here](https://github.com/conda/constructor/blob/main/CONSTRUCT.md#post_install). TLDR: Using PREFIX is the right way.

Excellent. Thanks for the clarification.

> * I am not sure why the `python` symlink is still needed, but I haven't tried to set up napari shortcuts yet. The `spyder` file you see now it's a signed C launcher that calls `spyder-script` in a subprocess. Shouldn't that be enough to keep the process "within the .app directory"? :( If not, I guess we could modify the launcher to accept "arbitrary arguments" of what process to launch, but "arbitrary" and C scares me 😬

What I think is happening is
* macOS requires the launch "executable" to be a compile executable for security reasons. The C launcher satisfies this. 👍🏼 
* macOS integrates the _bundle_ containing the _executable_. This will be the C launcher if no other command or script is executed. But since it executes an external shell script `spyder-script`, then whatever executable is executed therein breaks the integration. This executable could be specified by the shebang line or elsewhere in the script.
See https://github.com/spyder-ide/spyder/issues/18870#issuecomment-1245964252 and subsequent discussion.

I don't think having arbitrary arguments to the C launcher will necessarily resolve the issue. I think that the final executable call needs to appear to originate from within the bundle. I only see one of two ways to achieve this:
1. Provide a symbolic link in the bundle that is referenced in the launch script, e.g. executable `spyder` calls shell script `spyder-script` which calls (symlink to) executable `Spyder.app/Contents/MacOS/python`. This is the _technique_ used by `Python.app`, applied to our own application. I don't know why a symlink is allowed to "trick" macOS into thinking the executable originates inside the bundle 🤷🏼‍♂️ , but it seems to work.
2. Fully integrate the launch script into the C launcher. I don't know how to do this, but it means compiling the C launcher at conda package creation time or installer creation time. This is the same idea I was accomplishing with `shc`.

**Comment by mrclary** [comment]
> And if that doesn't work, I guess we can temporarily symlink stuff as part of the shortcut logic to keep things in-house. Something like
> 
> ```python
> lines.append(f'ln -s "{command[0]}" "{app_location / "Contents" / "MacOS" / "_symlinked_executable"}"')
> # replace command[0] with symlink location and continue the rest of the logic
> ```

I'm not familiar with the internals of `menuinst`, but yes, I think this idea will work.
I suppose this would have to accommodate arbitrary executables, not just `python`. In my post-install script, I have
```shell
ENV_PREFIX=$(cd "${PREFIX}/envs/__NAME_LOWER__"; pwd)
app_path="$(dirname ${DSTROOT})/Applications/__NAME__.app"
ln -sf "${ENV_PREFIX}/bin/python" "${app_path}/Contents/MacOS/python"
```

**Comment by mrclary** [comment]
> Also, please note I am not an expert macOS user so I am not aware of many of the UX conventions. Is it to be expected that all applications "register" their keyboard shortcuts in the OS Preferences?

No, the application does not need to register its keyboard shortcuts in System Preferences. This is handled by Qt. macOS System Preferences provides a way for users to customize keyboard shortcuts for all applications or for specific applications. Spyder provides its own interface for customizing keyboard shortcuts (again, handled by Qt). I'm merely using the System Preferences keyboard shortcuts as a proxy for macOS integration. If I can add a shortcut to a (empty) menu item, then I'm confident that the application should be fully integrated with macOS.

**Comment by mrclary** [comment]
> ```shell
> ENV_PREFIX=$(cd "${PREFIX}/envs/__NAME_LOWER__"; pwd)
> app_path="$(dirname ${DSTROOT})/Applications/__NAME__.app"
> ln -sf "${ENV_PREFIX}/bin/python" "${app_path}/Contents/MacOS/python"
> ```

Actually, this only works if the `extra_envs` is the same name as the base environment. It appears that `__NAME_LOWER__` is the name of the base environment, e.g. `~/Library/__NAME_LOWER__` and the name(s) of `extra_envs` is not available to the post-install script.

**Comment by jaimergp** [comment]
Menuinst will have access to the env prefix, so that should be ok. The post-install scripts only needs to know about the `base` env prefix (root installation) because theoretically speaking the other environments you create are controlled by the installer creation process, not the end user choice.

I'll look into the symlink stuff for macOS this weekend!

**Comment by jaimergp** [comment]
And thanks for the super helpful messages, really appreciate it @mrclary!

**Comment by jaimergp** [comment]
An implementation for this feature is now available. [Check this example for guidelines](https://github.com/jaimergp/menuinst/blob/324250b4d8d16a2d859349e7e7ef0c15038a5b15/tests/data/jsons/osx_symlinks.json#L10-L19), @mrclary! The idea is to symlink any executable _into_ the bundle, and then use the placeholder to use it in the `command` script. More manual than initially intended, but also more explicit and less magic. Hopefully that's enough!

Packages are also in `napari/label/bundle_tools_2` now.

**Comment by mrclary** [comment]
@jaimergp, that looks really good. I'll check it out next week.

**Comment by jaimergp** [comment]
Happy new year @mrclary! (when should one stop celebrating? 😂)

Did you get a chance to check whether the last builds fix the issue?

**Comment by mrclary** [comment]
Happy new year to you, @jaimergp! Sorry I did not report back sooner, but I did check everything and it seems to work just great. Thanks for all your work!
I just merged in changes for Spyder that incorporates these updates and changes introduced in constructor 4.0b7.

BTW, did you see conda/menuinst#111?

**Comment by jaimergp** [comment]
Awesome! Thank you very much. Closing here and checking the other issue.
