### ISSUE TITLE
Add integration checks for cross-repository consistency

### ISSUE THREAD

**Issue by jaimergp** [napari/packaging#6]
As we work on an external repository, we must ensure that somethings stay in sync. Most of it can be done by simply cloning `napari/napari`, but the packaging metadata should be consistent across repos, specially for the PyPI <-> conda interactions and dependencies.

**Comment by potating-potato** [comment]
not sure if I follow what is to be completed here, but I hope we have a single source of truth for metadata than having multiple ones that we have to check that they are in sync

**Comment by jaimergp** [comment]
We had a long discussion about the feasibility of unifying metadata in https://github.com/napari/napari/pull/4404 - the conclusion was that it adds so much hackery that it's not worth it :(

**Comment by potating-potato** [comment]
> We had a long discussion about the feasibility of unifying metadata in [napari/napari#4404](https://github.com/napari/napari/pull/4404) - the conclusion was that it adds so much hackery that it's not worth it :(

thanks for the reference! This seems to be about setup.cfg vs environment.yml etc. I am not getting into this holy war myself then

**Comment by jaimergp** [comment]
I ended up adding a different mechanism. If `napari/napari` receives a `push` to `main` with changes to `setup.cfg`, an issue will be created tagging me so I take a look. Not perfect, but I don't anticipate much traffic in that file.

**Comment by potating-potato** [comment]
going to close this for now given we have a temporary workaround
