### ISSUE TITLE
Prepare 0.4.18 release

### ISSUE THREAD

**Issue by Czaki** [napari/packaging#73]
The branch https://github.com/napari/napari/tree/v0.4.18x of napari repo is going in nice direction to release. 
What I should do to also run a bundle build for it?

**Comment by jaimergp** [comment]
Go to https://github.com/napari/packaging/actions/workflows/make_bundle_conda.yml and run the workflow using the branch name, I think!

**Comment by Czaki** [comment]
https://github.com/napari/packaging/actions/runs/5376969379/jobs/9755205122

As I understand, workflow requires crate napari release on conda?

**Comment by jaimergp** [comment]
No, the packages are pre-generated in the first step, locally. There's a bug in the pipeline, that's all. I'll look into it, sorry!

**Comment by jaimergp** [comment]
0.4.18rc2 artifacts available at https://github.com/napari/packaging/actions/runs/5410466633

**Comment by kephale** [comment]
@lauramarcos is testing `0.4.18rc2` from (https://github.com/napari/packaging/actions/runs/5410466633) and noticed that if you have a previous version of the bundled app installed you get this error cascade:
![image](https://github.com/napari/packaging/assets/400105/60ede2aa-d568-4a4b-a570-5babb74c4f5c)
and
![image](https://github.com/napari/packaging/assets/400105/13fb27cf-c230-4d60-8d2e-cb4aa75d5e34)

Can we show a warning dialog that prompts the user for a choice to install over an existing install?

**Comment by jaimergp** [comment]
Not possible PKGs, unfortunately. There is no notion of interactivity when choosing a target path, so we have to go all in (overwrite without prompting) or all out (bail and tell the user to relaunch). It's weird that 0.4.18rc2 existed though, this sounds like a reattempt? And also, Laura, are you trying to install in your user folder or in the root disk (`/`)?

**Comment by ctrueden** [comment]
Can this be closed? I downloaded [this napari 0.4.18 Linux bundle](https://github.com/napari/napari/releases/download/v0.4.18/napari-0.4.18-Linux-x86_64.sh) today so presumably the release was successfully prepared? :laughing:

**Comment by jaimergp** [comment]
As you have seen with the other issues, there are a couple things to polish before we regenerate the installers and close this one 😬
