### ISSUE TITLE
Installer script's "conda init" nukes existing conda config

### ISSUE THREAD

**Issue by ctrueden** [napari/packaging#79]
I have a mambaforge installation at `~/mambaforge` on my machine, with corresponding `.zshrc` block lovingly cradled by `>>> conda initialize >>>` markers. Today I installed the napari 0.4.18 bundle, which set up its own conda into `~/.local/napari-0.4.18`. After installation is complete, it asked me if I wanted to let it `conda init`, and I said yes naively, which caused my `.zshrc` block to be overwritten with the napari-0.4.18 one.

This seems odd, because one would imagine that a use case of constructor is to allow for multiple such installers to operate on the same system and coexist peacefully. I checked the constructor issue tracker for any such reports of such things *not* working, but didn't find anything in a couple minutes of searching.

**Comment by jaimergp** [comment]
`constructor` does not go that far, but we should remove the `conda init` question from the napari installer because I can't see how it would help anyone anyway. Thanks for the report!
